config:
  send_anonymous_usage_stats: false

jaffle_shop:
  outputs:
    default:
      type: postgres
      threads: 1
      host: localhost
      port: 7547
      user: postgres
      pass: password
      dbname: postgres
      schema: jaffle
